

input:
  model_path: ./model_folder
  data_path: "data/sample"

search:
  doc_search:
    max_doc: 10
  vec_search:
    max_results: 15
    embedding_model: "all-MiniLM-L6-v2"

generate:
  generate_num: 1
  model_name: "Jumtra/rinna-3.6b-tune-ep5"
  use_fast: True # True if use Jumtra model else False
